services:
  postgres:
    image: postgres:16-alpine
    container_name: chatlog-postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chatlog-network

  app:
    image: vvqhuy1999/chatlog:latest
    container_name: chatlog-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - chatlog-network

  frontend:
    image: vvqhuy1999/log-chatbot-frontend:latest
    container_name: log-chatbot-frontend
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - chatlog-network

volumes:
  postgres_data:

networks:
  chatlog-network:
    driver: bridge