-- =============================================
-- Chức năng: Định nghĩa cấu trúc database để lưu trữ các cuộc trò chuyện.
-- Bao gồm 2 bảng chính:
-- 1. chat_sessions: Quản lý các phiên chat (cuộc trò chuyện).
-- 2. chat_messages: Lưu trữ nội dung tin nhắn của từng phiên chat.
-- =============================================

-- Sử dụng PostgreSQL: Kết nối tới database 'chatlog' trước 

-- Mỗi "New Chat" của người dùng sẽ là một dòng trong bảng này.
CREATE TABLE IF NOT EXISTS chat_sessions (
  session_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  title VARCHAR(255) DEFAULT 'Cuộc trò chuyện mới',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  last_active_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (session_id)
);

-- Bảng này chứa nội dung chi tiết của các cuộc trò chuyện.
-- Liên kết với `chat_sessions` qua `session_id`.
CREATE TABLE IF NOT EXISTS chat_messages (
  message_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  session_id BIGINT NOT NULL,
  sender VARCHAR(10) NOT NULL CHECK (sender IN ('USER', 'AI')),
  content TEXT NOT NULL,
  "timestamp" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (message_id),
  CONSTRAINT fk_message_session
    FOREIGN KEY (session_id)
    REFERENCES chat_sessions (session_id)
    ON DELETE CASCADE -- Quan trọng: Nếu một session bị xóa, tất cả tin nhắn cũng bị xóa.
);

-- Chỉ mục thường dùng cho truy vấn
CREATE INDEX IF NOT EXISTS idx_chat_sessions_last_active ON chat_sessions (last_active_at);
CREATE INDEX IF NOT EXISTS idx_chat_messages_session_time ON chat_messages (session_id, "timestamp");

/*
-- Trigger tự động cập nhật last_active_at khi có tin nhắn mới
CREATE OR REPLACE FUNCTION update_session_last_active_on_message()
RETURNS TRIGGER AS $$
BEGIN
  UPDATE chat_sessions
  SET last_active_at = CURRENT_TIMESTAMP
  WHERE session_id = NEW.session_id;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER chat_messages_after_insert
AFTER INSERT ON chat_messages
FOR EACH ROW
EXECUTE FUNCTION update_session_last_active_on_message();

-- Trigger tự động "chạm" last_active_at khi bản ghi chat_sessions được cập nhật
CREATE OR REPLACE FUNCTION touch_last_active()
RETURNS TRIGGER AS $$
BEGIN
  NEW.last_active_at := CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER chat_sessions_before_update
BEFORE UPDATE ON chat_sessions
FOR EACH ROW
EXECUTE FUNCTION touch_last_active();
*/
-- =============================================
-- VÍ DỤ VỀ CÁCH THÊM DỮ LIỆU
-- =============================================


-- Seed datasets cho test nhanh
-- Session 1: Hỏi về SQL (mới hoạt động gần đây)
INSERT INTO chat_sessions (title, created_at, last_active_at)
VALUES ('Hỏi về SQL', NOW() - INTERVAL '2 days', NOW() - INTERVAL '10 minutes');

-- Session 2: Lên kế hoạch du lịch (hoạt động hôm qua)
INSERT INTO chat_sessions (title, created_at, last_active_at)
VALUES ('Lên kế hoạch du lịch', NOW() - INTERVAL '6 days', NOW() - INTERVAL '1 day');

-- Session 3: Lập trình Java (hoạt động 3 ngày trước)
INSERT INTO chat_sessions (title, created_at, last_active_at)
VALUES ('Lập trình Java', NOW() - INTERVAL '10 days', NOW() - INTERVAL '3 days');

-- Giả sử id tương ứng lần lượt là 1, 2, 3
INSERT INTO chat_messages (session_id, sender, content, "timestamp") VALUES
(1, 'USER', 'Làm thế nào để tạo database?', NOW() - INTERVAL '2 days'),
(1, 'AI', 'Dùng câu lệnh CREATE DATABASE trong PostgreSQL.', NOW() - INTERVAL '47 hours'),
(1, 'USER', 'Cách tạo bảng và khóa ngoại?', NOW() - INTERVAL '3 hours'),
(1, 'AI', 'Dùng CREATE TABLE và FOREIGN KEY, ví dụ...', NOW() - INTERVAL '2 hours');

INSERT INTO chat_messages (session_id, sender, content, "timestamp") VALUES
(2, 'USER', 'Tư vấn lịch trình du lịch Đà Nẵng 3 ngày.', NOW() - INTERVAL '6 days'),
(2, 'AI', 'Gợi ý: Ngày 1 Bà Nà, Ngày 2 Sơn Trà - Hội An...', NOW() - INTERVAL '5 days'),
(2, 'USER', 'Ước tính chi phí khoảng bao nhiêu?', NOW() - INTERVAL '1 day');

INSERT INTO chat_messages (session_id, sender, content, "timestamp") VALUES
(3, 'USER', 'Làm sao cấu hình Spring Boot với PostgreSQL?', NOW() - INTERVAL '10 days'),
(3, 'AI', 'Thêm dependency, cấu hình application.yaml, dùng HikariCP...', NOW() - INTERVAL '9 days'),
(3, 'USER', 'Có ví dụ về repository không?', NOW() - INTERVAL '3 days');

-- Lấy danh sách phiên chat mới nhất trước
-- SELECT * FROM chat_sessions ORDER BY last_active_at DESC;

/*
select * from chat_sessions;
select * from chat_messages;
*/



